### PR TITLE
Add a README to experiments/ with replication instructions

### PR DESCRIPTION
**Pull request by erikcs**
Add a README to the `experiments/` folder explaining the following folder content:

- [x] Athey and Wager (2019): This replication material is already complete.

- [x] Athey, Tibshirani, and Wager (2019) 
    - This is reorganized into a separate folder. 
    - The original R script and data for Figure 3 is _added_ and modified with comparable settings for the latest grf version (1.2.0). The data is a small (xz zipped by R) csv file containing only columns used for the analysis.
    - A simple script for Table 1 is _added_

- [x] Friedberg, Tibshirani, Athey, and Wager (2018): This replication material is already complete.

- [x] Mayer, Sverdrup, Gauss, Moyer, Wager, and Josse (2020): This replication material is already complete.

- [x] Wager and Athey (2018): Add a link to the deprecated `causalForest` package.

No replication material is modified in this PR.

### CODE REVIEW

**Comment by swager** [comment]
Thanks @erikcs for putting this together! One thing, though: The WA18 paper isn't based on the GRF package (it used older ad-hoc code), so we shouldn't have replication files for it here. (For anyone who wants to replicate experiments from WA18, one can go to https://github.com/swager/causalForest; however, I don't recommend using the implementation there.)

**Comment by erikcs** [comment]
Got it @swager, that entry has been updated.

**Comment by erikcs** [comment]
I moved all ATW19 related files into a separate `aos19` folder https://github.com/erikcs/grf/tree/update-replications/experiments 

What remains is data (Angrist and Evans, modified or stored somewhere else) for Figure 3

**Comment by erikcs** [comment]
This experiments folder should be self contained now with all the original replication material, including a version of the Angrist-Evans data that fits in a git repository.

Note that I have not rerun the angrist example as the biggest computer I had access to (Sherlock) did not have enough RAM for 100 k trees.  I did also not make any changes to the replication material to account for later changes in grfs parameter names, etc.

**Pull request merged**
