### PR TITLE
Instrument forest Warning Correction

### PR DESCRIPTION
**Pull request by ginward**
I think originally the warnings given in average_late is incorrect. 

The `if` condition was to compare `z.hat`:

`if (min(subset.Z.hat) <= 0.01 || max(subset.Z.hat) >= 0.99)`

While the warning messages gives the range of W.hat:

`rng <- range(subset.W.hat)`

And the warning on treatment propensities: 

`Estimated treatment propensities take values between
`

However, z.hat is the instrument propensity, not the treatment propensity. I don't understand why we would compare the instrument propensity and gives warnings on treatment propensity. 

Shouldn't we change the if statement to compare `w.hat`, if we gives warnings on `w.hat`? 

I am not sure if this warning message is trying to warn `Z.hat` or `W.hat`.  So I added warning messages for both. 

Note that, I think the warnings on W.hat only makes sense if the variable is binary. So I have also added a condition to check that. 

Referring to #490 and #553

### CODE REVIEW

**Comment by ginward** [comment]
Furthermore, I added the absolute value operator for the compliance score warnings: 

`if (abs(min(subset.compliance.score)) <= 0.01 * sd(subset.W.orig))
`
The reason is that, if W is continuous, it is possible that Z will results in a decrease in W, which results in a negative compliance score. Therefore, I think it only makes sense to include an absolute value in front of the compliance score.

**Comment by swager** [comment]
Thanks @ginward. For the first point, the code flow was correct; there's only a typo in the error message, i.e., W.hat being close to 0 or 1 is not a problem.

**Comment by ginward** [comment]
Thanks @swager 

How about the absolute value point?

**Comment by ginward** [comment]
> Thanks @ginward. For the first point, the code flow was correct; there's only a typo in the error message, i.e., W.hat being close to 0 or 1 is not a problem.

If w.hat is binary, there might still be a problem if it is close to 0 and 1?

**Comment by ginward** [comment]
> Thanks @swager
> 
> How about the absolute value point?

Or rather, if Z causes W to decrease, it violates the Monotonicity assumption in the   (Imbens and Angrist 1994) paper: 

Screenshot 2019-11-01 at 20 41 04

Do you see any way to circumvent that? @swager 

Because my instrument could cause the treatment variable to decrease ... Does flipping the sign help?

**Comment by swager** [comment]
That's what the check on the compliance score is for. If the instrument is weak, the compliance score is close to 0. Yes, good catch, we should have an absolute value for the compliance score check.

**Comment by ginward** [comment]
> That's what the check on the compliance score is for. If the instrument is weak, the compliance score is close to 0. Yes, good catch, we should have an absolute value for the compliance score check.

Thanks @swager 

My worry is that, if the monotonicity assumption is violated (i.e. if my instrument causes the continuous treatment to decrease), I cannot use average_late to calculate the average treatment effect anymore.  If I am correct, the average_late function is based on Imbens and Angrist 1994 paper, isn't it? The monotonicity assumption is one of the crucial assumptions in the paper. 

If that is the case, we probably don't need the absolute sign, as the negative value cause will automatically be invalid ... 

Let me know what you think. @swager

**Comment by ginward** [comment]
> That's what the check on the compliance score is for. If the instrument is weak, the compliance score is close to 0. Yes, good catch, we should have an absolute value for the compliance score check.

Thanks @swager

My worry is that, if the monotonicity assumption is violated (i.e. if my instrument causes the continuous treatment to decrease), I cannot use average_late to calculate the average treatment effect anymore.  If I am correct, the average_late function is based on Imbens and Angrist 1994 paper, isn't it? The monotonicity assumption is one of the crucial assumptions in the paper. 

If that is the case, we probably don't need the absolute sign, as the negative value cause will automatically be invalid ... 

Let me know what you think. @swager

**Comment by ginward** [comment]
> That's what the check on the compliance score is for. If the instrument is weak, the compliance score is close to 0. Yes, good catch, we should have an absolute value for the compliance score check.

Thanks @swager 

My worry is that, if the monotonicity assumption is violated (i.e. if my instrument causes the continuous treatment to decrease thus have a negative subset.compliance.score), I cannot use average_late to calculate the average treatment effect anymore.  If I am correct, the average_late function is based on Imbens and Angrist 1994 paper, isn't it? The monotonicity assumption is one of the crucial assumptions in the paper. 

If that is the case, we probably don't need the absolute sign, as the negative value cause will automatically be invalid ... 

Let me know what you think. @swager

**Comment by ginward** [comment]
Thanks @swager 

I suspect that the current implementation of average_late only supports binary treatment only. 

Because the compliance score is estimated as: 

Delta(X) = E[W | X, Z = 1] - E[W | X, Z = 0]     (1)

The definition of compliance score is: 

Delta(X) = P[ [W | X, Z = 1] - E[W | X, Z = 0] >0 ]    (2)

I think (1) only equals (2) when W is binary. However, currently the package only restricted Z to be binary. 

We either need to restrict W as well to be binary as well, or we will need to re-define a compliance score that works for non-binary treatment W.

**Comment by ginward** [comment]
It is also not immediately clear to me how Inverse Compliance Score Weighting applies to non-binary treatment. So probably it is a good idea to restrict treatment W is binary? @swager

**Comment by ginward** [comment]
I also think that the [documentation](https://cran.r-project.org/web/packages/grf/grf.pdf) is not correct: 

"When W is binary and there are no "defiers", Imbens and Angrist
(1994) show that tau(x) can be interpreted as an average treatment effect on compliers."

I think, in the function, you implemented the Inverse Compliance Score Weighted ATE? If that is the case according to Aronow and Carnegie 2013, it is effectively the average treatment effect for all, not only just for the compliers, no?

**Comment by ginward** [comment]
\

> Thanks @swager
> 
> I suspect that the current implementation of `average_late` only supports **binary** treatment only.
> 
> Because the compliance score is estimated as (Athey and Wager 2017):
> 
> `Delta(X) = E[W | X, Z = 1] - E[W | X, Z = 0] (1)`
> 
> The definition of compliance score is (Aronow and Carnegie 2013):
> 
> `Delta(X) = P[ W(Z=1) - W(Z=0) > 0 | X ] (2)`
> 
> I think (1) only equals (2) when `W` is binary. However, currently the package only restricted `Z` to be binary.
> 
> We either need to restrict `W` as well to be binary as well, or we will need to re-define a compliance score that works for non-binary treatment `W`.

I am thinking if it is possible to estimate Compliance Score  when W is continuous with the following approach: 

1) Calculate `Delta(X) = E[W | X, Z = 1] - E[W | X, Z = 0] `

2) Set a dummy `k = 1` when `Delta(X) > 0` and `k = 0` when `Delta(X) < 0`

3) Estimate `P(k=1|X) `with a regression forest, and use `P(k=1|X)` as the compliance score. 

Do you think this will work? @swager

**Comment by ginward** [comment]
I have required W to be binary at this point.

**Comment by swager** [comment]
We should keep this PR discussion on-topic, focused on the first two fixes in the early commit (the typo in the comment, plus the absolute value for the compliance score check).

I'm happy to have a broader conversation about interpretation of local average treatment effects in the context of continuous exposures, but here is not the right place for it.

Also, just to be clear, the function average_late supports continuous treatments. We do not need to (and should not) insert a check that W is binary. (Yes in fact Abadie & Aronow/Carnegie work with a binary treatment, but one can check that the definitions & results generalize seamlessly.)

**Comment by ginward** [comment]
Thanks @swager 

I have removed the check for binary `w` from the commit. Please see if the commit is now ready to be merged.

**Comment by ginward** [comment]
Thanks. 

Can @erikcs merge the request?

**Pull request merged**
